name: example
description: Interactively evaluate FHIRPath expressions
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fhir: ^0.12.0
  fhir_path:
    path: ../../fhir_path
  google_fonts: ^4.0.4
  url_launcher: ^6.1.11
  yaml_writer: ^1.0.3

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

dependency_overrides:
  meta: ^1.12.0
