name: fhir_path
description: FHIRPath navigation and extraction language implemented in pure Dart to be used with base FHIR packages.
version: 0.11.3
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_path

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  fhir_dstu2:
    path: ../fhir_dstu2
  fhir_primitives:
    path: ../fhir_primitives
  fhir_r4:
    path: ../fhir_r4
  fhir_r5:
    path: ../fhir_r5
  fhir_r6:
    path: ../fhir_r6
  fhir_stu3:
    path: ../fhir_stu3
  ucum:
    path: ../ucum
  petitparser: ^6.0.2

dev_dependencies:
  # flutter pub run import_sorter:main
  import_sorter: ^4.6.0
  lints: ^3.0.0
  test: ^1.25.2
